---
name: qwiet.ai

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    #container: shiftleft/core:latest
    
    steps:
    - uses: actions/checkout@v3


    - name: preZero Static Analysis
      run: |
        export QWIET_ENABLE_MULTI_LANGUAGE_ANALYSIS=true
        mkdir temp
        chmod -wx temp
        #sl analyze --strict --wait --verbose --app java-js-python .
        docker run --rm -t --name slcore -e SHIFTLEFT_ACCESS_TOKEN="$SHIFTLEFT_ACCESS_TOKEN" -e QWIET_ENABLE_MULTI_LANGUAGE_ANALYSIS=true -v $PWD:/app -v $PWD/temp:/tmp shiftleft/core sl analyze --verbose --app  java-python-js /app
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
